# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: make new json

on:
    schedule:
        - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: make json
      env:
        TZ: Asia/Tokyo
      run:
        python src/scraping.py
    - name: Commit files
      env:
        TZ: Asia/Tokyo
      run: |
        TODAY=`date "+%Y/%m/%d %H:%M"`
        git config --local user.email "63353429YanaseT@users.noreply.github.com"
        git config --local user.name "YanaseT"
        git status | grep modified && git add src/ && git commit -v -m "[Bot] データ更新 ${TODAY}" \
          && curl -X POST \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/YanaseT/covid19-ichihara/dispatches --data '{"event_type": "build_application"}' \
          || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
